- name: install docker
  yum:
    name=docker
    update_cache=yes
    state=present

- name: enable docker
  systemd:
    name: docker
    enabled: yes
    state: started

# Proxy configuration based on the documents
#   https://docs.docker.com/config/daemon/systemd/
# alternatives; setting /etc/sysconfig/docker may also works
#   https://docs.docker.com/network/proxy/
- name: proxy configuration directory (if configured)
  file: path=/etc/systemd/system/docker.service.d state=directory
  when: USE_PROXY is defined
- name: proxy configuration file (if configured)
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  when: USE_PROXY is defined

- name: reload systemd for docker proxy configuration
  systemd:
    daemon_reload: yes
- name: restart docker for proxy configuration
  systemd:
    name: docker
    state: restarted
  changed_when: false

- name: check docker images
  command: docker images centos:centos7 -q
  changed_when: false
  register: result
- name: download docker images
  command: docker pull centos:centos7
  when: result.stdout == ''
