- name: create bundle log directory
  include_tasks: container-prepare.yml
  loop_control:
    loop_var: bundle_name
  with_items:
    - "httpd-bundle-0"
    - "httpd-bundle-1"

- name: pull container images
  command: docker pull {{ item }}
  with_items:
    - "{{ APPS_POSTGRES_IMAGE }}"
    - "{{ APPS_HTTPD_IMAGE }}"
