- name: make sure that working directory exists
  file:
    path: "{{ KUBE_WORK_DIR }}"
    state: directory

- name: generate cib.xml configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ KUBE_WORK_DIR }}/{{ item }}"
  with_items:
    - bundle-all-cib.xml

- name: apply cib.xml configuration
  command: cibadmin --modify --xml-file {{ KUBE_WORK_DIR }}/bundle-all-cib.xml
